### PR TITLE
BaseVideo: add lengthSeconds field

### LINKED ISSUE #49: Get video length
**Is your feature request related to a problem? Please describe.**
I would like to get the length of a video

**Describe the solution you'd like**
A `lengthSeconds` key in the `video` object would be great

**Describe alternatives you've considered**
Manually making the request?

### PR DESCRIPTION
**Pull request by MaxLeiter**
closes #49

### CODE REVIEW

**Comment by MaxLeiter** [comment]
I'm a fool and missed duration

**Comment by SuspiciousLookingOwl** [comment]
`Video` and `LiveVideo` extends `BaseVideo`, `Video` has duration, `LiveVideo` doesn't. `BaseVideo` supposed to not have `duration`

**Comment by MaxLeiter** [comment]
Ah I see, `getVideo` returns `Video | LiveVideo | undefined`. How can I work with just Video?

**Comment by SuspiciousLookingOwl** [comment]
You can narrow type using if else like this
```ts
import {Client, Video, LiveVideo} from "youtubei";

const youtubei = new Client();

const video = await youtubei.getVideo("abc");
if (video) {
    if (video instanceof Video) {
        // video is instanceof Video
        console.log(video.duration); // no error
    } else {
        // video is instanceof LiveVideo
        console.log(video.duration); // error
    }
}
```
[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMIBtgFMB2MA0cBqwAJuhHgDLABu6hJEAvnAGZQQhwBEAnhAK4w+AI3TBOAbgBQkgMYRMAZ3i8Bw0XAC8cTOgDucVBmwAKAJRTZ8pXCrFSmuAENdj4Mv6CRwAHQBzdDB0pMacjkIynOaSwMxwxrb0poiScKlwMXEJ9sCKMI6YMqSxQRBJCClplQD0VTZ2EOkK6bn5hRDF9RWVqXKKECjo3igQvvH13kR8UI4wwPLmcDXaDehQbFBdcEzoKAroyd1pS1kNwE05Sq1FcJQ0JZuVvQr9g8OjJxNTM3OYC0ur602DEkDCAA)

I also added generic type on `.getVideo` to easily narrow down type, although less safe
```ts
import {Client, Video} from "youtubei";

const youtubei = new Client();

const video = await youtubei.getVideo<Video>("abc");
console.log(video.duration); // no error
```

**Comment by MaxLeiter** [comment]
ah the generic is perfect. thanks

**Pull request closed without merging**
